"""Publish /back-office: widget "3VL Page Back Office" (page.html / page.css / page.js, generated by the build script)
inside web page "back-office" (created on first run). Share image via BD redirect share/back-office-v1.jpg.
    python site/back-office/deploy.py"""
import json, os, sys, urllib.parse, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "share-img"))
from bdkey import key

H = {"X-Api-Key": key(), "User-Agent": "Mozilla/5.0 3VL", "Content-Type": "application/x-www-form-urlencoded"}
API = "https://www.threevillagelocal.com/api/v2/"
NAME = "3VL Page Back Office"
SLUG = "back-office"
TITLE = "The Back Office: Local Pros for Business Owners | Three Village Local"
DESC = ("Accountants, payroll, employee benefits, business insurance, commercial lending, legal, IT, marketing and commercial "
        "cleaning: trusted local pros for business owners in Setauket, Stony Brook and Port Jefferson. Free printable toolbox.")
SHARE_SRC = "https://threevillagelocal-cloud.github.io/3vl-share/site/back-office/share-v1.jpg"


def call(method, path, data=None):
    body = urllib.parse.urlencode(data).encode() if data is not None else None
    return json.loads(urllib.request.urlopen(urllib.request.Request(API + path, data=body, headers=H, method=method), timeout=60).read())


def rd(f):
    s = open(os.path.join(HERE, f), encoding="utf-8").read()
    assert "\\" not in s, f + " has a backslash (BD strips them)"
    return s


def main():
    w = {"widget_data": rd("page.html"), "widget_style": rd("page.css"), "widget_javascript": rd("page.js")}
    found = call("GET", "data_widgets/get?property=widget_name&property_value=" + urllib.parse.quote(NAME)).get("message")
    found = [x for x in found if x.get("widget_name") == NAME] if isinstance(found, list) else []
    if found:
        print("widget", found[0]["widget_id"], call("PUT", "data_widgets/update", dict(w, widget_id=found[0]["widget_id"])).get("status"))
    else:
        r = call("POST", "data_widgets/create", dict(w, widget_name=NAME, widget_viewport="front"))
        print("widget create", r.get("status"), (r.get("message") or {}).get("widget_id") if isinstance(r.get("message"), dict) else r.get("message"))
    # share image redirect (BD mangles external og URLs)
    red = call("GET", "redirect_301/get?property=old_filename&property_value=share/back-office-v1.jpg").get("message")
    if not (isinstance(red, list) and red):
        print("redirect", call("POST", "redirect_301/create", {"old_filename": "share/back-office-v1.jpg", "new_filename": SHARE_SRC}).get("status"))
    page = {"content": "[widget=%s]" % NAME, "content_css": " ", "enable_hero_section": "0", "title": TITLE, "meta_desc": DESC,
            "facebook_title": "The Back Office: local pros who keep your business running", "facebook_desc": DESC,
            "facebook_image": "https://www.threevillagelocal.com/share/back-office-v1.jpg"}
    ex = call("GET", "list_seo/get?property=filename&property_value=" + SLUG).get("message")
    ex = [x for x in ex if x.get("filename") == SLUG] if isinstance(ex, list) else []
    if ex:
        r = call("PUT", "list_seo/update", dict(page, seo_id=ex[0]["seo_id"]))
    else:
        r = call("POST", "list_seo/create", dict(page, seo_type="content", filename=SLUG, nickname="The Back Office"))
    print("page", r.get("status"), r.get("message") if r.get("status") != "success" else (r.get("message") or {}).get("seo_id", ""))
    try:
        call("POST", "website_settings/refreshCache", {})
    except Exception as ex:
        print("cache:", ex)


if __name__ == "__main__":
    main()
